# Generated by Django 4.1 on 2022-08-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro_categoria_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
