# Generated by Django 4.1 on 2022-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carro_categoria_carro_cor_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
