# Generated by Django 4.1 on 2022-08-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carro_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
    ]
